// Datos de productos (simulando una base de datos)
const products = [
    {id: 1, name: "Hamburguesa simple", price: 6.00, category: "hamburguesa", image: "images/productos/h-simple.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 2, name: "Hamburguesa royal", price: 7.50, category: "hamburguesa", image: "images/productos/h-royal.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 3, name: "Hamburguesa hawaiana", price: 9.00, category: "hamburguesa", image: "images/productos/h-hawaiana.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 4, name: "Hamburguesa chorizo", price: 8.00, category: "hamburguesa", image: "images/productos/h-chorizo.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 5, name: "Hamburguesa cubana", price: 8.50, category: "hamburguesa", image: "images/productos/h-cubana.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 6, name: "Pollo broaster + papas + ensalada + arroz", price: 10.00, category: "broaster", image: "images/productos/pollo-broaster.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 7, name: "Alitas broaster + papas + ensalada + arroz", price: 10.00, category: "broaster", image: "images/productos/alitas-broaster.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 8, name: "Salchipapa", price: 7.00, category: "otros", image: "images/productos/salchipapa.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 9, name: "Salchipollo", price: 9.00, category: "otros", image: "images/productos/salchipollo.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 10, name: "Patitas", price: 5.00, category: "otros", image: "images/productos/patitas.webp",
    tags: ["Mayonesa", "Ají", "Mostaza", "Aceituna", "Ketchu" , "Sin ensalada", "Sin tomate", "Sin cremas", "Cremas aparte"]},
    {id: 11, name: "Jugo de Mango", price: 4.00, category: "jugos", image: "images/productos/jugo-mango.webp",
    tags: ["Helado", "Sin helar"]},
    {id: 12, name: "Jugo de Naranja", price: 4.00, category: "jugos", image: "images/productos/jugo-naranja.webp",
    tags: ["Helado", "Sin helar"]},
    {id: 13, name: "Jugo de Piña", price: 6.00, category: "jugos", image: "images/productos/jugo-pina.webp",
    tags: ["Helado", "Sin helar"]},
    {id: 14, name: "Jugo de Fresa", price: 6.00, category: "jugos", image: "images/productos/jugo-fresa.webp",
    tags: ["Helado", "Sin helar"]},
    {id: 15, name: "Jugo de Fresa con leche", price: 7.00, category: "jugos", image: "images/productos/jugo-fresaleche.webp",
    tags: ["Helado", "Sin helar"]},
    {id: 16, name: "Huevo", price: 1.50, category: "adicionales", image: "https://placehold.co/300x200",
    tags: []},
    {id: 17, name: "Platano", price: 1.00, category: "adicionales", image: "https://placehold.co/300x200",
    tags: []},
    {id: 17, name: "Queso", price: 2.00, category: "adicionales", image: "https://placehold.co/300x200",
    tags: []},
    {id: 18, name: "Piña", price: 2.00, category: "adicionales", image: "https://placehold.co/300x200",
    tags: []},
    {id: 19, name: "Arroz", price: 2.00, category: "adicionales", image: "https://placehold.co/300x200",
    tags: []},
    {id: 20, name: "Gaseosa (preguntar)", price: 0, category: "adicionales", image: "https://placehold.co/300x200",
    tags: ["Helada", "Sin helar"]},
    {id: 20, name: "Refresco del día (preguntar)", price: 0, category: "adicionales", image: "https://placehold.co/300x200",
    tags: ["Helado", "Sin helar"]},
];